### ISSUE TITLE
version for symfony 2.* not usable - api key

### ISSUE THREAD

**Issue by grekpg** [ollietb/OhGoogleMapFormTypeBundle#37]
I use dev-master version for symfony 2.8 - now dev-master is for 3.* symfony. 
How i can setup maps api key ? (now google maps not work without key)

**Comment by xmon** [comment]
In my fork this is possible, https://github.com/xmon/OhGoogleMapFormTypeBundle.

I create a pull request but it isn't merge yet, since last updates appears some conflicts with my pull request. https://github.com/ollieLtd/OhGoogleMapFormTypeBundle/pull/17 

I use my fork in 3 differents projects, and works like a charm.

I hope this helps.

**Comment by ollietb** [comment]
@grekpg ive updated the composer requirements
